import { createHash } from 'node:crypto';
import type { BuiltinLocale, LocalizedText, ResolvedLanguage, TemplateProfile } from './types.js';

export const LOCALE_RESOLVER_VERSION = 1;

const ENGLISH_ALIASES = new Set(['english', 'en', 'en-us']);
const CHINESE_ALIASES = new Set(['chinese', 'simplified chinese', 'zh', 'zh-cn', 'zh-hans']);

function stableSerialize(value: unknown): string {
  if (Array.isArray(value)) {
    return `[${value.map(stableSerialize).join(',')}]`;
  }
  if (value !== null && typeof value === 'object') {
    const record = value as Record<string, unknown>;
    return `{${Object.keys(record)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${stableSerialize(record[key])}`)
      .join(',')}}`;
  }
  return JSON.stringify(value);
}

function isLocalizedText(value: unknown): value is LocalizedText {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;
  const keys = Object.keys(value as Record<string, unknown>).sort();
  return keys.length === 2 && keys[0] === 'en' && keys[1] === 'zh-CN';
}

function collectLocalizedValues(
  value: unknown,
  locale: BuiltinLocale,
  path: string,
  result: Array<{ path: string; value: string }>,
): void {
  if (isLocalizedText(value)) {
    result.push({ path, value: value[locale] });
    return;
  }
  if (Array.isArray(value)) {
    value.forEach((item, index) =>
      collectLocalizedValues(item, locale, `${path}[${index}]`, result),
    );
    return;
  }
  if (value !== null && typeof value === 'object') {
    const record = value as Record<string, unknown>;
    for (const key of Object.keys(record).sort()) {
      collectLocalizedValues(record[key], locale, path ? `${path}.${key}` : key, result);
    }
  }
}

function computeLocaleFingerprint(profile: TemplateProfile, locale: BuiltinLocale): string {
  const localizedValues: Array<{ path: string; value: string }> = [];
  collectLocalizedValues(profile, locale, '', localizedValues);
  return createHash('sha256')
    .update(
      stableSerialize({
        localeResolverVersion: LOCALE_RESOLVER_VERSION,
        profileId: profile.id,
        profileRevision: profile.revision,
        resolvedLocale: locale,
        localizedValues,
      }),
    )
    .digest('hex');
}

function normalizeRequestedLanguage(value?: string): { value: string; valid: boolean } {
  const normalized = (value ?? '')
    .replace(/[\x00-\x1F\x7F]/g, '')
    .trim()
    .slice(0, 50);
  return { value: normalized, valid: normalized === '' || /^[a-zA-Z -]+$/.test(normalized) };
}

export function resolveLanguage(
  requestedLanguage: string | undefined,
  profile: TemplateProfile,
): ResolvedLanguage {
  const normalized = normalizeRequestedLanguage(requestedLanguage);
  let resolvedLocale: BuiltinLocale = 'en';
  let fallbackFrom: string | undefined;
  const diagnostics: Array<{
    code: 'invalid-language' | 'unsupported-locale-fallback';
    message: string;
  }> = [];

  if (!normalized.valid) {
    diagnostics.push({
      code: 'invalid-language',
      message: 'The requested language is invalid; deterministic content uses English.',
    });
  } else if (CHINESE_ALIASES.has(normalized.value.toLowerCase())) {
    resolvedLocale = 'zh-CN';
  } else if (normalized.value !== '' && !ENGLISH_ALIASES.has(normalized.value.toLowerCase())) {
    fallbackFrom = normalized.value;
    diagnostics.push({
      code: 'unsupported-locale-fallback',
      message: `Built-in text is unavailable for ${normalized.value}; deterministic content uses English.`,
    });
  }

  return {
    requestedLanguage: normalized.valid ? normalized.value : '',
    resolvedLocale,
    ...(fallbackFrom ? { fallbackFrom } : {}),
    localeFingerprint: computeLocaleFingerprint(profile, resolvedLocale),
    localeResolverVersion: LOCALE_RESOLVER_VERSION,
    diagnostics,
  };
}

export function localize(text: LocalizedText, language: ResolvedLanguage): string {
  return text[language.resolvedLocale];
}

export interface WikiPresentationMessages {
  overview: string;
  modules: string;
  loading: string;
  pageNotFound: string;
  generatedBy: string;
  coverageTitle: string;
  section: string;
  required: string;
  status: string;
  evidence: string;
  yes: string;
  no: string;
  statusLabels: Record<'verified' | 'inferred' | 'missing' | 'conflicting' | 'needs-human', string>;
}

const PRESENTATION_MESSAGES: Record<BuiltinLocale, WikiPresentationMessages> = {
  en: {
    overview: 'Overview',
    modules: 'Modules',
    loading: 'Loading…',
    pageNotFound: 'Page not found',
    generatedBy: 'Generated by GitNexus',
    coverageTitle: 'Profile Coverage',
    section: 'Section',
    required: 'Required',
    status: 'Status',
    evidence: 'Evidence',
    yes: 'Yes',
    no: 'No',
    statusLabels: {
      verified: 'Verified',
      inferred: 'Inferred',
      missing: 'Missing',
      conflicting: 'Conflicting',
      'needs-human': 'Needs human review',
    },
  },
  'zh-CN': {
    overview: '概览',
    modules: '章节',
    loading: '加载中…',
    pageNotFound: '页面不存在',
    generatedBy: '由 GitNexus 生成',
    coverageTitle: 'Profile 覆盖情况',
    section: '章节',
    required: '必需',
    status: '状态',
    evidence: '证据',
    yes: '是',
    no: '否',
    statusLabels: {
      verified: '已验证',
      inferred: '推断',
      missing: '缺失',
      conflicting: '冲突',
      'needs-human': '需要人工确认',
    },
  },
};

export function getWikiPresentationMessages(language: ResolvedLanguage): WikiPresentationMessages {
  return PRESENTATION_MESSAGES[language.resolvedLocale];
}
